% Enter the info of the subject
prompt      = {'N:';...
    'Name:';...
    'Gender:';...
    'Age:';...
    'Handness:';...
    'Languages:';...
    'Debug';...
    'DebugAudio';...
    'MEG';...
    'EyeTracker';...
    'Use Bitsi'};

defans      = {'99';...
    'xxx';...
    'f';...
    '25' ;...
    'r';...
    'n';...
    '0';...
    '0';...
    '0';...
    '0';...
    '0'};

answer = inputdlg(prompt,'Subject Info',1,defans);

E.sbj.n       = str2double(answer{1});
E.sbj.name    = answer{2};
E.sbj.gender  = answer{3};
E.sbj.age     = str2double(answer{4});
E.sbj.hand    = answer{5};
E.sbj.lang    = answer{6};
E.useDev.debugmode  = logical(str2double(answer{7}));
E.useDev.debugaudio = logical(str2double(answer{8}));
E.useDev.useMEG     = logical(str2double(answer{9}));
E.useDev.useET      = logical(str2double(answer{10}));
E.useDev.useBitsi   = logical(str2double(answer{11}));